import type { Metadata } from "next";
import { siteConfig } from "@/data/site";
const paragraphs = [
  "Build the Pyramid Wiki helps players understand verified Build the Pyramid! tasks and tools.",
  "Build the Pyramid Wiki editorial publishes this site and separates verified facts from unknown or changing details.",
  "Build the Pyramid Wiki is an independent, unofficial fan resource for the Roblox game Build the Pyramid! (Janitors Studios). It is not affiliated with or endorsed by Janitors Studios or Roblox."
];
const officialLinks: Array<{ href: string; label: string; detail: string }> = [
  { href: "https://www.roblox.com/games/123720558354386/Build-the-Pyramid", label: "Roblox game page", detail: "The official place to play Build the Pyramid! (place 123720558354386)." },
  { href: "https://www.roblox.com/groups/907940218/Janitors-Studios", label: "Janitors Studios group", detail: "The studio's Roblox group (owner Ariex / ariex6000), also behind Clean the Manga Shop!." },
  { href: "https://discord.gg/9sksDM6r8M", label: "Studio Discord", detail: "Verified September 23, 2026: the invite resolves to the Janitors Studios server whose description names Build the Pyramid! (about 4,200 members). The studio posts update notes and code strings in its #updates and #announcements channels." }
];
const officialStatus = "Checked September 23, 2026: an official Trello and an official wiki still do not exist for this game; unofficial wikis and code sites are not official surfaces. This page keeps the checked date instead of guessing.";
export const metadata: Metadata = { title: "About this site and the official Build the Pyramid! links", description: "What this site is, plus the verified official Build the Pyramid! surfaces: Roblox game page, Janitors Studios group, and the studio Discord (status checked September 23, 2026).", alternates: { canonical: `${siteConfig.domain}/about/` }, robots: { index: true, follow: true } };
export default function SystemPage() { return <main className="mx-auto grid w-full max-w-4xl gap-6 px-4 py-10 sm:py-14"><header className="rounded-3xl border border-white/10 bg-white/[0.04] p-6 sm:p-9"><p className="text-sm font-extrabold uppercase tracking-[0.18em] text-pink-200">Build the Pyramid Wiki</p><h1 className="mt-3 text-4xl font-black text-white">About this site</h1></header><section className="grid gap-4 rounded-3xl border border-white/10 bg-slate-950/45 p-6 sm:p-9">{paragraphs.map((paragraph, index) => index === 1 && paragraph.includes("@") ? <a key={index} href={`mailto:${paragraph}`} className="font-bold text-cyan-200 underline underline-offset-4">{paragraph}</a> : <p key={index} className="leading-8 text-white/78">{paragraph}</p>)}</section><section aria-labelledby="official-links-heading" className="rounded-3xl border border-cyan-300/20 bg-cyan-400/[0.06] p-6 sm:p-9"><h2 id="official-links-heading" className="text-2xl font-black text-cyan-100">Official Build the Pyramid! links (checked September 23, 2026)</h2><ul className="mt-5 grid gap-4">{officialLinks.map((link) => <li key={link.href} className="rounded-2xl border border-white/10 bg-slate-950/45 p-5"><a href={link.href} rel="noopener noreferrer" target="_blank" className="text-lg font-bold text-cyan-200 underline underline-offset-4">{link.label}</a><p className="mt-2 leading-7 text-white/75">{link.detail}</p></li>)}</ul><p className="mt-5 leading-7 text-white/65">{officialStatus}</p></section></main>; }
